name: Update README

on:
  schedule:
    - cron: '0 0 * * *'  # Запускать ежедневно в полночь
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Update README
        uses: anmol098/waka-readme-stats@v2.0.1  # Убедитесь, что используете последнюю доступную версию
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Использование PAT вместо GITHUB_TOKEN
          DEBUG_LOGGING: true


